user_generator:
  cron: "*/5 * * * *"
  class: "UserGeneratorJob"
  queue: "default"
  retry: 0

transaction_generator:
  cron: "*/15 * * * *"
  class: "TransactionGeneratorJob"
  queue: "default"
  retry: 0
